# Generated by Django 6.0.4 on 2026-04-16 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('impacto_temperatura', models.IntegerField()),
                ('impacto_energia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.IntegerField(default=37)),
                ('energia', models.IntegerField(default=100)),
                ('recursos', models.IntegerField(default=0)),
                ('dias_sobrevividos', models.IntegerField(default=0)),
                ('esta_vivo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
